### ISSUE TITLE
Login時の地域選択で対象リージョン追加

### ISSUE THREAD

**Issue by sakon310** [cloud-handson/iks-handson-setup#1]
ソウルリージョンが3番目に差し込まれたため、それ以降の番号ズレが発生しているようです。

    3. kr-seo
    4. eu-de
    5. eu-gb
    6. us-south
    7. us-east
    Enter a number> 6                < us-southを選択。

**Comment by kota661** [comment]
ご指摘ありがとうございます。修正いたしました！
